EPMRPP-67056 - add github workflow
reportportal/agent-js-webdriverio pull request #10
Opened 2021-09-28 11:21 UTC by chivekrodis

2021-09-29 10:58 UTC, AmsterGet requested changes
Also please add corresponding files:
VERSION
version_fragment
CHANGELOG.MD

2021-09-29 10:58 UTC, AmsterGet commented on .github/workflows/CI-pipeline.yml
> +        run: npm run test:coverage
Also please check the build command execution here and in the `publish` workflow file as [here](https://github.com/reportportal/agent-js-playwright/blob/master/.github/workflows/CI-pipeline.yml#L38).

2021-09-29 10:58 UTC, AmsterGet commented on src/reportingApi.ts
> +  setStatus: (status: RP_STATUSES | string, suite?: string): void =>
Why we need to support custom strings here?

2021-09-29 10:58 UTC, AmsterGet commented on package.json
> +    "node": ">= 12.0.0"
We do not support node.js versions lower than `12.x`?

2021-09-29 11:13 UTC, chivekrodis commented on package.json
> +    "node": ">= 12.0.0"
webdriver [drop-node-v10-support](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/#drop-node-v10-support)
So I decided set up min.v.12

2021-09-30 07:47 UTC, AmsterGet requested changes

2021-09-30 07:47 UTC, AmsterGet commented on VERSION
> +5.0.0
Please add a `-SNAPSHOT` postfix as this version not released yet.

2021-09-30 07:47 UTC, AmsterGet commented on package.json
>    "version": "5.0.0",
Also please make this version (here and in the `package-lock.json`) lower than 5, f.e. `4` - this is needed for the first release, then it will be incremented automatically.

2021-09-30 08:08 UTC, AmsterGet approved these changes

2021-09-30 08:08 UTC, merged