EPMRPP-78031 || Implement selenium logs reporting
reportportal/agent-js-webdriverio pull request #31
Opened 2022-07-22 10:06 UTC by Bam6ycha

2022-07-25 09:48 UTC, chivekrodis requested changes

2022-07-25 09:48 UTC, chivekrodis commented on CHANGELOG.md
> +## [5.0.3] - 2022-07-25
Release tag will be set up automatically. remove it here

2022-07-25 09:48 UTC, chivekrodis commented on README.md
> +  seleniumCommandsLogLevel:'debug',
Please use styling to be more consistent

2022-07-25 09:48 UTC, chivekrodis commented on README.md
> +seleniumCommandsLogLevel | If set *reportSeleniumCommands* to *true*, you need to provide log level witch can be one of: *'debug', 'info', 'warn', 'error', 'fatal'*. |
We have `trace` level

2022-07-25 09:48 UTC, chivekrodis commented on src/reporter.ts
> +  onRunnerStart({ isMultiremote }: Partial<RunnerStats>): void {
Maybe better leave it just `onRunnerStart(runnerStats)` this config has alot of info it might be usefull in the future

2022-07-25 09:48 UTC, chivekrodis commented on src/__tests__/onAfterCommand.spec.ts
> +    jest.clearAllMocks();
Can you show where are you use mock object to use clearAllMocks after it?

2022-07-25 09:48 UTC, chivekrodis commented on src/__tests__/onRunnerStart.spec.ts
> +  const runner: Partial<RunnerStats> = { isMultiremote: false };
Better `runnerOptions` or `runnerStats`

2022-07-25 09:48 UTC, chivekrodis commented on src/__tests__/utils.spec.ts
> +  });
Can you please also check some positive result or more complex?

2022-07-25 13:53 UTC, chivekrodis requested changes

2022-07-25 13:53 UTC, chivekrodis commented on src/__tests__/onBeforeCommand.spec.ts
> +    reporterSpyOn.mockClear();
Looks like better move back previous solution as  that more clear
```js
  afterEach(() => {
    jest.clearAllMocks();
  });
```

2022-07-25 13:53 UTC, chivekrodis commented on src/__tests__/onAfterCommand.spec.ts
>      const reporterSpyOn = jest.spyOn(reporter['client'], 'sendLog');
Why you try spyOn `sendLog` here but on line 70 you not?

2022-07-25 13:53 UTC, chivekrodis commented on src/__tests__/utils.spec.ts
> +      expect(limit(user)).toEqual({ age: 20, id: 1, name: 'User' });
You can re-use user obj

2022-07-25 13:53 UTC, chivekrodis commented on src/__tests__/utils.spec.ts
> +        name: 'UserName',
Objects almost the same. You can create something like code down below to try reuse info
```js
const baseUser = {
        name: 'UserName',
        surname: 'UserSurname',
        fullName: 'UserName UserSurname',
        age: 21,
        id: 2,
        tel: '12345',
        eMail: 'absdefg@yourMail.com',
        address: 'Some address',
        password: '*****',
        role: 'Some role',
      };
const user = {...baseUser,   hobbies: 'Some hobbies',}
const expectedObj = {...baseUser,  _: `1 more keys: [\"hobbies\"]`,}
```

2022-07-25 13:53 UTC, chivekrodis commented on src/__tests__/utils.spec.ts
> +      const array = new Array(9).fill('some value');
If you expected the same value please reuse it

2022-07-25 14:36 UTC, chivekrodis requested changes

2022-07-25 14:36 UTC, chivekrodis commented on src/__tests__/utils.spec.ts
>          role: 'Some role',
Why role not in the baseUser or in the excluded keys?

2022-07-25 14:36 UTC, chivekrodis commented on src/__tests__/utils.spec.ts
> +      const valuesArray = [...baseValues, 'some value', 'some value'];
same here for 'some value'

2022-07-25 14:51 UTC, chivekrodis approved these changes

2022-07-25 14:51 UTC, chivekrodis approved these changes

2022-07-26 08:27 UTC, AmsterGet approved these changes

2022-07-26 08:27 UTC, merged