EPMRPP-80662 || Browser parameter
reportportal/agent-js-webdriverio pull request #37
Opened 2022-11-08 10:52 UTC by tr1ble

2022-11-08 11:22 UTC, AmsterGet requested changes

2022-11-08 11:22 UTC, AmsterGet commented on src/reporter.ts
> +      parameters: [this.sanitizedCapabilities && getBrowserParam(this.sanitizedCapabilities)],
I guess we should not report parameters in case of empty.

2022-11-08 11:22 UTC, AmsterGet commented on src/__tests__/onTestStart.spec.ts
> +      },
Please add test for existing parameters.

2022-11-08 11:22 UTC, AmsterGet commented on src/utils.ts
> +};
Cover with tests or just provide this object directly in `onTestStart`.

2022-11-08 13:27 UTC, chivekrodis requested changes

2022-11-08 13:27 UTC, chivekrodis commented on src/reporter.ts
> +      parameters: browser && [{ key: BROWSER_PARAM, value: browser }],
I guess better write like this to omit key if `this.sanitizedCapabilities=false`
`...(this.sanitizedCapabilities && {parameters: [{ key: BROWSER_PARAM, value: browser }]})`
And variable `browser` looks unnecessary here

2022-11-08 13:27 UTC, chivekrodis commented on src/reporter.ts
> +    this.sanitizedCapabilities = runnerStats.sanitizedCapabilities;
Please move it higher close to `isMultiremote` to extract all params from `runnerStats` in the same place

2022-11-08 13:27 UTC, chivekrodis commented on src/reporter.ts
> +const BROWSER_PARAM = 'browser';
Better move to constant file

2022-11-10 09:58 UTC, chivekrodis approved these changes

2022-11-10 10:34 UTC, AmsterGet approved these changes

2022-11-10 10:34 UTC, merged