EPMRPP-65592 - attach last error log to description
reportportal/agent-js-webdriverio pull request #9
Opened 2021-09-20 08:28 UTC by chivekrodis

Base must be changed after merging [EPMRPP-65590](https://github.com/reportportal/agent-js-webdriverio/pull/8) to develop.

2021-09-20 17:17 UTC, AmsterGet requested changes

2021-09-20 17:17 UTC, AmsterGet commented on src/reporter.ts
> +          testStats.errors[testStats.errors.length - 1].stack
Why not just `error`?

2021-09-20 17:17 UTC, AmsterGet commented on src/reporter.ts
> +        }
Can be simplified:
```javascript
this.storage.updateCurrentTest({
   description: testItem.description ? `${testItem.description}\n${lastError}` : lastError,
});
```

2021-09-21 06:50 UTC, chivekrodis commented on src/reporter.ts
> +          testStats.errors[testStats.errors.length - 1].stack
`error` is declared in upper scope

2021-09-21 06:55 UTC, AmsterGet requested changes

2021-09-21 06:55 UTC, AmsterGet commented on src/reporter.ts
> +          testStats.errors[testStats.errors.length - 1].stack
I'm talking about the object you are using to get the `stack`.
Why not use an existing `error` object instead of `testStats.errors [testStats.errors.length - 1] `, in your case, `idx === testStats.errors.length - 1`, so `error` will be the same as `testStats.errors [testStats.errors.length - 1]` or `testStats.errors [idx]`.

2021-09-21 07:12 UTC, AmsterGet approved these changes

2021-09-21 09:05 UTC, merged